name: Build App

on:
  push:
    branches:
      - dev_code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build
